import App_ from './App/App';
import CreateDraft_ from './CreateDraft/CreateDraft';
import CreatePlayer_ from './CreatePlayer/CreatePlayer';
import CreateTeam_ from './CreateTeam/CreateTeam';
import DraftMenu_ from './DraftMenu/DraftMenu';
import Drafts_ from './Drafts/Drafts';
import LoggedInView_ from './LoggedInView/LoggedInView';
import LoggedOutView_ from './LoggedOutView/LoggedOutView';
import Login_ from './Login/Login';
import MainMenu_ from './MainMenu/MainMenu';
import Players_ from './Players/Players';
import Register_ from './Register/Register';
import Requests_ from './Requests/Requests';
import TeamMenu_ from './TeamMenu/TeamMenu';
import Teams_ from './Teams/Teams';
import UpdateUser_ from './UpdateUser/UpdateUser';

export const App = App_;
export const CreateDraft = CreateDraft_;
export const CreatePlayer = CreatePlayer_;
export const CreateTeam = CreateTeam_;
export const DraftMenu = DraftMenu_;
export const Drafts = Drafts_;
export const LoggedInView = LoggedInView_;
export const LoggedOutView = LoggedOutView_;
export const Login = Login_;
export const MainMenu = MainMenu_;
export const Players = Players_;
export const Register = Register_;
export const Requests = Requests_;
export const TeamMenu = TeamMenu_;
export const Teams = Teams_;
export const UpdateUser = UpdateUser_;
